name: test-chmod
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "content" > test.file
        ls -la test.file
        chmod 0000 test.file
        ls -la test.file
        cat test.file
